# config/routes.yaml
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Import all the routes from annotations
annotations:
    resource: ../src/Controller/
    type: annotation
