# config/routes.yaml
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Import all the routes from annotations
annotations:
    resource: ../src/Controller/
    type: annotation

api_platform:
    resource: .
    type: api_platform
    prefix: /api

# config/routes.yaml
docs:
    path: /docs
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /api/docs
        permanent: true