# config/routes.yaml
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Import all the routes from annotations
annotations:
    resource: ../src/Controller/
    type: annotation

api_refresh_token:
    path: /api/token/refresh
  
api_platform:
    resource: .
    type: api_platform
    prefix: /api

api_reservations:
    path: /api/reservations
    controller: App\Controller\ReservationController::createReservation
    methods: POST

