const createSlotFormFields = [
    {
        type: 'number',
        name: 'performance_id',
        label: 'ID de la performance',
        required: true,
    },
    {
        type: 'number',
        name: 'number_of_clients',
        label: 'Nombre de clients',
        required: true,
    },
    {
        type: 'select',
        name: 'week_day',
        label: 'Jour de la semaine',
        options: [
            { value: 'lundi', label: 'Lundi' },
            { value: 'mardi', label: 'Mardi' },
            { value: 'mercredi', label: 'Mercredi' },
            { value: 'jeudi', label: 'Jeudi' },
            { value: 'vendredi', label: 'Vendredi' },
            { value: 'samedi', label: 'Samedi' },
            { value: 'dimanche', label: 'Dimanche' },
        ],
        required: true,
    },
    {
        type: 'date',
        name: 'day_start_at',
        label: 'Date de début',
        required: true,
    },
    {
        type: 'date',
        name: 'day_end_at',
        label: 'Date de fin',
        required: true,
    },
    {
        type: 'select',
        name: 'time_start_at',
        label: 'Heure de début',
        options: [
            { value: '06:00', label: '06:00' },
            { value: '07:00', label: '07:00' },
            { value: '08:00', label: '08:00' },
            { value: '09:00', label: '09:00' },
            { value: '10:00', label: '10:00' },
            { value: '11:00', label: '11:00' },
            { value: '12:00', label: '12:00' },
            { value: '13:00', label: '13:00' },
            { value: '14:00', label: '14:00' },
            { value: '15:00', label: '15:00' },
            { value: '16:00', label: '16:00' },
            { value: '17:00', label: '17:00' },
            { value: '18:00', label: '18:00' },
            { value: '19:00', label: '19:00' },
            { value: '20:00', label: '20:00' },
        ],
        required: true,
    },
    {
        type: 'select',
        name: 'duration_minutes',
        label: 'Durée (minutes)',
        options: [
            { value: 30, label: '30 minutes' },
            { value: 45, label: '45 minutes' },
            { value: 60, label: '1 heure' },
            { value: 120, label: '2 heures' },
            { value: 240, label: '4 heures' },
            { value: 360, label: '5 heures' },
            { value: 480, label: '6 heures' },
        ],
        required: true,
    },
    {
        type: 'text',
        name: 'time_end_at',
        label: 'Heure de fin',
        required: true,
        readOnly: true,
    },
];

export default createSlotFormFields;
