version: '3.7'

services:
  php:
    image: ${IMAGES_PREFIX:-}app-php
    depends_on:
      - database
    environment:
      PWA_UPSTREAM: pwa:3000
      SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
      TRUSTED_HOSTS: ^${SERVER_NAME:-example\.com|localhost}|php$$
      DATABASE_URL: postgres://uf23ihl7so67pt:pd38f3c373b543b9697bb476f73804135fa474d6637a4b7fc481272f3b6e99696@caij57unh724n3.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/dem34k3cmh9r2
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp

  database:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=dem34k3cmh9r2
      - POSTGRES_PASSWORD=pd38f3c373b543b9697bb476f73804135fa474d6637a4b7fc481272f3b6e99696
      - POSTGRES_USER=uf23ihl7so67pt
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  caddy_data:
  caddy_config:
  db_data:
