api_platform:
<<<<<<< HEAD
    title: Hello API Platform
    version: 1.0.0
    # Mercure integration, remove if unwanted
=======
    title: 'Challenge - API Platform'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json:
            - 'application/merge-patch+json'
    swagger:
        versions: [3]
    http_cache:
        invalidation:
            enabled: true
        public: true
    mercure:
        enabled: false  
>>>>>>> refs/remotes/origin/feat/dashboard
    formats:
        jsonld:  ['application/ld+json']
        json:    ['application/json']
        html:    ['text/html']
        jsonhal: ['application/hal+json']
    exception_to_status:
        Symfony\Component\Serializer\Exception\ExceptionInterface: 400 # Bad request on deserialization errors
