vich_uploader:
    db_driver: orm

    mappings:
       brand_pdf:
           uri_prefix: /fichiers/brands
           upload_destination: '%kernel.project_dir%/public/fichiers/brands'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
       brand_image:
           uri_prefix: /images/brands
           upload_destination: '%kernel.project_dir%/public/images/brands'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
