apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: back
build:
  artifacts:
    - image: back-php
      context: ../api
      docker:
        target: app_php
    - image: back-pwa
      context: ../pwa
      docker:
        target: prod

deploy:
  kubeContext: minikube
  helm:
    releases:
    - name: back
      chartPath: ./back
      namespace: default
      setValueTemplates:
        php.image.repository: "{{.IMAGE_REPO_api_platform_php}}"
        php.image.tag: "{{.IMAGE_TAG_api_platform_php}}@{{.IMAGE_DIGEST_api_platform_php}}"
        pwa.image.repository: "{{.IMAGE_REPO_api_platform_pwa}}"
        pwa.image.tag: "{{.IMAGE_TAG_api_platform_pwa}}@{{.IMAGE_DIGEST_api_platform_pwa}}"
      valuesFiles:
        - skaffold-values.yaml
