name: Back CI

on:
  push:
    branches:
      - prod
    paths:
      - 'back/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./back

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start API Platform Docker containers
        run: docker-compose up -d

      - name: Install dependencies
        run: docker-compose exec -it php composer install

      - name: Execute Doctrine migration
        run: docker-compose exec php bin/console make:migration

      - name: Load Doctrine fixtures
        run: docker-compose exec php bin/console doctrine:migrations:migrate

