name: Back CI

on:
  push:
    branches:
      - prod
    paths:
      - 'back/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./back

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Increase Swap Space
        run: |
          sudo fallocate -l 4G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          free -h

      - name: Start API Platform Docker containers
        run: docker compose up -d

      - name: Clear Composer Cache
        run: docker compose exec php composer clear-cache

      - name: Install dependencies
        run: docker compose exec php composer install --no-interaction --no-cache --optimize-autoloader

      - name: Execute Doctrine migration
        run: docker compose exec php bin/console make:migration

      - name: Load Doctrine fixtures
        run: docker compose exec php bin/console doctrine:migrations:migrate
      
    # - name: Run linting
    #   run: docker-compose exec -it php composer run-script lint

    # - name: Run test
    #   run: docker-compose exec -it php bin/phpunit
