name: Back CI

on:
  push:
    branches:
      - main
    paths:
      - 'back/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./back

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start API Platform Docker containers
        run: docker-compose up -d

      - name: Install dependencies
        run: docker compose exec -it php composer install

#      - name: Execute Doctrine migration
#        run: docker-compose exec -it php bin/console doctrine:migrations:migrate --no-interaction

      #      - name: Load Doctrine fixtures
      #        run: docker-compose exec -it php bin/console doctrine:fixtures:load --no-interaction

      - name: Run linting
        run: docker-compose exec -it php composer run-script lint

      - name: Run test
        run: docker-compose exec -it php bin/phpunit
