name: Back CI

on:
  push:
    branches:
      - feature/CiCd
    paths:
      - 'back/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./back

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Start API Platform Docker containers
        run: docker-compose up -d

      - name: Install dependencies
        run: docker compose exec -it php composer install

      - name: Run linting
        run: docker-compose exec -it php composer run-script lint
