name: Back CI

on:
  push:
    branches:
      - prod
    paths:
      - 'back/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./back

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start API Platform Docker containers
        run: docker-compose up -d

      - name: Wait for PHP container to be ready
        run: |
          echo "Waiting for PHP container to be ready..."
          until docker-compose exec php ls /var/www; do
            sleep 5
          done

      - name: Install dependencies
        run: docker-compose exec php composer install

      - name: Execute Doctrine migration
        run: docker-compose exec php bin/console doctrine:migrations:migrate --no-interaction

      - name: Load Doctrine fixtures
        run: docker-compose exec php bin/console doctrine:fixtures:load --no-interaction

      - name: Run test
        run: docker-compose exec php bin/phpunit
