name: Deploy Back-End To Heroku

on:
  push:
    branches:
      - prod
    paths:
      - 'api/**'
      - '.github/workflows/heroku-deploy.yml'

jobs:
  
  build:
    needs:
      - tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back/api
    steps:
      - uses: actions/checkout@v4
      - uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "planifit"
          heroku_email: "khsuwang@myges.fr"
          appdir: "api"