name: Deploy Back-End To Heroku

on:
  push:
    branches:
      - prod
    paths:
      - 'back/api/**'
      - '.github/workflows/heroku-deploy.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true 
      - run: git subtree split --prefix=back/api HEAD
      - run: git push --force heroku `git subtree split --prefix=back/api HEAD`:refs/heads/main
      - uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "planifit"
          heroku_email: "khsuwang@myges.fr"
          appdir: "back/api"
